# Generated by Django 6.0.2 on 2026-02-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['name'], 'verbose_name': 'Facility', 'verbose_name_plural': 'Facilities'},
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('diagnostic_center', 'Diagnostic Center'), ('urgent_care', 'Urgent Care'), ('specialty_center', 'Specialty Center'), ('other', 'Other')], default='clinic', help_text='Type of healthcare facility', max_length=20),
        ),
        migrations.AddField(
            model_name='facility',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude coordinate', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.TextField(help_text='Full physical address of the facility'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the facility was created'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the facility is currently active'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(help_text='Name of the healthcare facility', max_length=200),
        ),
        migrations.AlterField(
            model_name='facility',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number for the facility', max_length=15, null=True),
        ),
    ]
