# Generated by Django 6.0.2 on 2026-03-07 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Django user account linked to this facility', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilityrouting',
            name='age_group',
            field=models.CharField(blank=True, choices=[('newborn', 'Newborn (0-2 months)'), ('infant', 'Infant (2-12 months)'), ('child_1_5', 'Child (1-5 years)'), ('child_6_12', 'Child (6-12 years)'), ('teen', 'Teen (13-17 years)'), ('adult', 'Adult (18-64 years)'), ('elderly', 'Elderly (65+ years)')], help_text='Patient age group from triage', max_length=20, null=True, verbose_name='age group'),
        ),
        migrations.AddField(
            model_name='facilityrouting',
            name='patient_village',
            field=models.CharField(blank=True, help_text='Patient village/subcounty from triage', max_length=100, null=True, verbose_name='patient village'),
        ),
        migrations.AddField(
            model_name='facilityrouting',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other / Prefer not to say')], help_text='Patient sex from triage', max_length=20, null=True, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='facilityrouting',
            name='patient_district',
            field=models.CharField(blank=True, help_text='Patient district/area from triage', max_length=100, null=True, verbose_name='patient district'),
        ),
    ]
