# Generated by Django 6.0.2 on 2026-03-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_user_facilityrouting_age_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='services_offered',
            field=models.JSONField(blank=True, default=list, help_text='Select medical services offered at the facility (choose from standardized list)', verbose_name='services offered'),
        ),
    ]
