# Generated by Django 6.0.2 on 2026-02-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_alter_facility_options_facility_ambulance_available_and_more'),
    ]

    operations = [
    ]
