# Generated by Django 6.0.2 on 2026-02-24 06:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_auto_20260218_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Overall match score (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('distance_km', models.FloatField(blank=True, help_text='Distance to patient in kilometers', null=True)),
                ('has_capacity', models.BooleanField(default=False, help_text='Facility has available capacity')),
                ('offers_required_service', models.BooleanField(default=False, help_text='Facility offers required services')),
                ('can_handle_emergency', models.BooleanField(default=False, help_text='Facility can handle emergency cases')),
                ('selection_reason', models.TextField(blank=True, help_text='Reason for facility selection')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'facility candidate',
                'verbose_name_plural': 'facility candidates',
                'ordering': ['-match_score'],
            },
        ),
        migrations.CreateModel(
            name='FacilityCapacityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_beds', models.IntegerField(help_text='Total beds at time of logging', null=True)),
                ('available_beds', models.IntegerField(help_text='Available beds at time of logging', null=True)),
                ('staff_count', models.IntegerField(help_text='Staff count at time of logging', null=True)),
                ('average_wait_time', models.IntegerField(help_text='Average wait time at time of logging', null=True)),
                ('beds_change', models.IntegerField(default=0, help_text='Number of beds added/removed')),
                ('change_reason', models.CharField(blank=True, help_text='Reason for capacity change', max_length=100)),
                ('change_notes', models.TextField(blank=True, help_text='Additional notes about the change')),
                ('source', models.CharField(default='manual', help_text='Source of the capacity update', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'facility capacity log',
                'verbose_name_plural': 'facility capacity logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilityNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_case', 'New Case'), ('confirmation', 'Confirmation'), ('cancellation', 'Cancellation'), ('update', 'Update'), ('reminder', 'Reminder')], default='new_case', max_length=20)),
                ('notification_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('subject', models.CharField(help_text='Notification subject line', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Structured payload for API notifications')),
                ('facility_response', models.JSONField(blank=True, help_text='Response data from facility', null=True)),
                ('response_received_at', models.DateTimeField(blank=True, help_text='When facility response was received', null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When notification was acknowledged', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When notification was sent', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'facility notification',
                'verbose_name_plural': 'facility notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilityRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_token', models.CharField(db_index=True, help_text='Anonymous patient identifier from Triage Agent', max_length=64, verbose_name='patient token')),
                ('triage_session_id', models.CharField(blank=True, help_text='Reference to triage session', max_length=100, verbose_name='triage session ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], help_text='Risk level from Triage Agent', max_length=20, verbose_name='risk level')),
                ('primary_symptom', models.CharField(help_text='Primary symptom from triage', max_length=100, verbose_name='primary symptom')),
                ('secondary_symptoms', models.JSONField(blank=True, default=list, help_text='Secondary symptoms from triage', verbose_name='secondary symptoms')),
                ('has_red_flags', models.BooleanField(default=False, help_text='Emergency red flags detected', verbose_name='has red flags')),
                ('chronic_conditions', models.JSONField(blank=True, default=list, help_text='Chronic conditions from triage', verbose_name='chronic conditions')),
                ('patient_district', models.CharField(help_text='Patient district/area', max_length=100, verbose_name='patient district')),
                ('patient_location_lat', models.FloatField(blank=True, help_text='Patient GPS latitude', null=True, verbose_name='patient latitude')),
                ('patient_location_lng', models.FloatField(blank=True, help_text='Patient GPS longitude', null=True, verbose_name='patient longitude')),
                ('booking_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], help_text='Whether booking is automatic or manual', max_length=20, verbose_name='booking type')),
                ('routing_status', models.CharField(choices=[('pending', 'Pending'), ('matching', 'Matching Facilities'), ('notified', 'Facility Notified'), ('confirmed', 'Confirmed by Facility'), ('rejected', 'Rejected by Facility'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='routing status')),
                ('facility_match_score', models.FloatField(blank=True, help_text='AI or rule-based matching score (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='facility match score')),
                ('distance_km', models.FloatField(blank=True, help_text='Distance to facility in kilometers', null=True, verbose_name='distance')),
                ('triage_received_at', models.DateTimeField(auto_now_add=True, help_text='When triage data was received', verbose_name='triage received at')),
                ('facility_notified_at', models.DateTimeField(blank=True, help_text='When facility was notified', null=True, verbose_name='facility notified at')),
                ('facility_confirmed_at', models.DateTimeField(blank=True, help_text='When facility confirmed booking', null=True, verbose_name='facility confirmed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'facility routing',
                'verbose_name_plural': 'facility routings',
                'ordering': ['-triage_received_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['name'], 'verbose_name': 'facility', 'verbose_name_plural': 'facilities'},
        ),
        migrations.AddField(
            model_name='facility',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.TextField(help_text='Physical address of the facility', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='ambulance_available',
            field=models.BooleanField(default=False, help_text='Whether ambulance service is available', verbose_name='ambulance available'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='available_beds',
            field=models.IntegerField(blank=True, help_text='Number of beds currently available', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='available beds'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='average_wait_time_minutes',
            field=models.IntegerField(blank=True, help_text='Average patient wait time in minutes', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='average wait time (minutes)'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('urgent_care', 'Urgent Care'), ('specialty_center', 'Specialty Center'), ('diagnostic_center', 'Diagnostic Center')], default='clinic', help_text='Type of healthcare facility', max_length=20, verbose_name='facility type'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the facility is currently operational', verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS latitude coordinate', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS longitude coordinate', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(help_text='Official name of the healthcare facility', max_length=200, verbose_name='facility name'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='notification_endpoint',
            field=models.URLField(blank=True, default='', help_text='API endpoint for receiving notifications', max_length=500, null=True, verbose_name='notification endpoint'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Primary contact phone number', max_length=20, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='services_offered',
            field=models.JSONField(blank=True, default=list, help_text='List of medical services offered at the facility', verbose_name='services offered'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='staff_count',
            field=models.IntegerField(blank=True, help_text='Number of medical staff on duty', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='staff count'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='total_beds',
            field=models.IntegerField(blank=True, help_text='Total number of beds available at the facility', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total beds'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['facility_type'], name='facilities__facilit_dd5426_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['is_active'], name='facilities__is_acti_a1584a_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['latitude', 'longitude'], name='facilities__latitud_c27960_idx'),
        ),
        migrations.AddField(
            model_name='facilitycandidate',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='facilitycapacitylog',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_logs', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='facilitynotification',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='facilityrouting',
            name='assigned_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routings', to='facilities.facility', verbose_name='assigned facility'),
        ),
        migrations.AddField(
            model_name='facilitynotification',
            name='routing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='facilities.facilityrouting'),
        ),
        migrations.AddField(
            model_name='facilitycandidate',
            name='routing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='facilities.facilityrouting'),
        ),
        migrations.AddIndex(
            model_name='facilitycapacitylog',
            index=models.Index(fields=['facility', 'created_at'], name='facilities__facilit_781c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitycapacitylog',
            index=models.Index(fields=['change_reason'], name='facilities__change__15691c_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitycapacitylog',
            index=models.Index(fields=['source'], name='facilities__source_476b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityrouting',
            index=models.Index(fields=['patient_token'], name='facilities__patient_3ca80b_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityrouting',
            index=models.Index(fields=['routing_status', 'triage_received_at'], name='facilities__routing_4bbe1d_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityrouting',
            index=models.Index(fields=['assigned_facility', 'routing_status'], name='facilities__assigne_e9c38b_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityrouting',
            index=models.Index(fields=['risk_level', 'triage_received_at'], name='facilities__risk_le_93b099_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitynotification',
            index=models.Index(fields=['facility', 'notification_status'], name='facilities__facilit_85b90e_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitynotification',
            index=models.Index(fields=['routing', 'notification_type'], name='facilities__routing_abf086_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitynotification',
            index=models.Index(fields=['notification_status', 'created_at'], name='facilities__notific_83b1ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facilitycandidate',
            unique_together={('routing', 'facility')},
        ),
    ]
