# Generated by Django 6.0.2 on 2026-03-06 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_facilityrouting_patient_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_token', models.CharField(db_index=True, help_text='Anonymous patient identifier', max_length=64, unique=True, verbose_name='patient token')),
                ('preferred_channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('ussd', 'USSD'), ('email', 'Email'), ('any', 'Any')], default='whatsapp', help_text='Patient preferred notification channel', max_length=20, verbose_name='preferred channel')),
                ('phone_number', models.CharField(blank=True, help_text='Patient phone number for notifications', max_length=20, verbose_name='phone number')),
                ('email_address', models.EmailField(blank=True, help_text='Patient email address for notifications', max_length=254, verbose_name='email address')),
                ('enable_facility_updates', models.BooleanField(default=True, help_text='Receive notifications about facility responses', verbose_name='enable facility updates')),
                ('enable_appointment_reminders', models.BooleanField(default=True, help_text='Receive appointment reminders', verbose_name='enable appointment reminders')),
                ('enable_case_updates', models.BooleanField(default=True, help_text='Receive general case status updates', verbose_name='enable case updates')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start time for quiet hours (no notifications)', null=True, verbose_name='quiet hours start')),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End time for quiet hours (no notifications)', null=True, verbose_name='quiet hours end')),
                ('language_preference', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('lg', 'Luganda')], default='en', help_text='Preferred notification language', max_length=10, verbose_name='language preference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Patient Notification Preference',
                'verbose_name_plural': 'Patient Notification Preferences',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_token', models.CharField(db_index=True, help_text='Anonymous patient identifier', max_length=64, verbose_name='patient token')),
                ('triage_session_id', models.CharField(blank=True, help_text='Related triage session', max_length=64, null=True, verbose_name='triage session ID')),
                ('notification_type', models.CharField(choices=[('facility_confirmed', 'Facility Confirmed'), ('facility_rejected', 'Facility Rejected'), ('alternative_facility', 'Alternative Facility'), ('bed_reserved', 'Bed Reserved'), ('appointment_scheduled', 'Appointment Scheduled'), ('case_update', 'Case Update'), ('reminder', 'Reminder')], help_text='Type of notification', max_length=30, verbose_name='notification type')),
                ('title', models.CharField(help_text='Notification title', max_length=200, verbose_name='title')),
                ('message', models.TextField(help_text='Full notification message', verbose_name='message')),
                ('delivery_channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('ussd', 'USSD'), ('email', 'Email'), ('web', 'Web')], default='whatsapp', help_text='How the notification was sent', max_length=20, verbose_name='delivery channel')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='pending', help_text='Delivery status of the notification', max_length=20, verbose_name='delivery status')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the notification was sent', null=True, verbose_name='sent at')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the notification was delivered', null=True, verbose_name='delivered at')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True, verbose_name='read at')),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed', verbose_name='error message')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of delivery attempts', validators=[django.core.validators.MaxValueValidator(5)], verbose_name='retry count')),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Additional notification data', verbose_name='additional data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('facility', models.ForeignKey(blank=True, help_text='Facility related to this notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_notifications', to='facilities.facility')),
                ('routing', models.ForeignKey(help_text='Related facility routing', on_delete=django.db.models.deletion.CASCADE, related_name='patient_notifications', to='facilities.facilityrouting')),
            ],
            options={
                'verbose_name': 'Patient Notification',
                'verbose_name_plural': 'Patient Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient_token', 'created_at'], name='facilities__patient_b9fb6b_idx'), models.Index(fields=['delivery_status', 'created_at'], name='facilities__deliver_3750fc_idx'), models.Index(fields=['notification_type', 'created_at'], name='facilities__notific_b4eeaa_idx'), models.Index(fields=['routing', 'notification_type'], name='facilities__routing_b9364c_idx')],
            },
        ),
    ]
