"""
Django settings for harakacare project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from pathlib import Path
import environ

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env()

# Read .env file (create one if needed)
env.read_env(os.path.join(BASE_DIR, '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-1n@#*!gtrob)l_%9lg6c-l5=!ix)wu5r807@_)zut(o1gttpxt')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "*",
"unprocreant-oswaldo-unsilently.ngrok-free.dev",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken',  # ← add this

    'apps.patients',
    'apps.triage',
    'apps.facilities',
    'apps.channels',
    'apps.adherence',
    'apps.analytics',
    'apps.core',
    'apps.conversations',
    'apps.messaging',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'harakacare.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'harakacare.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    }
}

# In base.py, add this:

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'apps': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

# HarakaCare Development Overrides
if 'HARAKACARE' in globals():
    HARAKACARE.update({
        'TRIAGE_SESSION_TIMEOUT': 600,  # 10 minutes for easier testing
        'USE_GPU': False,  # CPU-only for development
    })
else:
    HARAKACARE = {
        'TRIAGE_SESSION_TIMEOUT': 600,
        'USE_GPU': False,
    }

# Meta WhatsApp Cloud API credentials
META_WHATSAPP_ACCESS_TOKEN = env("META_WHATSAPP_ACCESS_TOKEN", default="")
META_WHATSAPP_PHONE_NUMBER_ID = env("META_WHATSAPP_PHONE_NUMBER_ID", default="")
META_WHATSAPP_WEBHOOK_VERIFY_TOKEN = env("META_WHATSAPP_WEBHOOK_VERIFY_TOKEN", default="harakacare_verify123")
META_WHATSAPP_APP_SECRET = env("META_WHATSAPP_APP_SECRET", default="")
META_WHATSAPP_BASE_URL = "https://graph.facebook.com"

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001", 
    "http://localhost:3002",
    "http://localhost:3003",
    "http://localhost:3004",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
    "http://127.0.0.1:3002",
    "http://127.0.0.1:3003",
    "http://127.0.0.1:3004",
    "https://unprocreant-oswaldo-unsilently.ngrok-free.dev",
]

CSRF_TRUSTED_ORIGINS = [
    "https://unprocreant-oswaldo-unsilently.ngrok-free.dev",
    "http://localhost:3000",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_ALL_ORIGINS = True

META_WHATSAPP_ACCESS_TOKEN = "EAAYAyFbrtwwBQZCA6CVWFqNH4sP6kLu9D819D16o9XjZBZCMZAlZAk94ZA8JpRkNWubv522xOGMU5RYul9hopshXZBZCJfwEcZChu1MmDd8yZBr2KYXRGeidHQMgWxP1wRUW4DPttLRAwPNxRpC0ZA2bDmpOl0TwXB1ZCjK1LWa5zUMYwF8j9BvtGe2hiRFKR56gM5SXkPcsTipbdRe3y6aGqMuhSYp5ZBiZBDINtBWolvLbFpWNs5id56yCUR3EXYLeRsbnpn9kcZA16o0dwf4rXG8fY49CAFv"
META_WHATSAPP_PHONE_NUMBER_ID = "996094946926174"
META_WHATSAPP_APP_SECRET = "9b48fef7bfe9598b44216f346a50a047"  # Temporarily empty for testing

print("🚀 Running in DEVELOPMENT mode")
