# Generated by Django 6.0.2 on 2026-02-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_token', models.CharField(max_length=40, unique=True)),
                ('step', models.CharField(default='start', max_length=30)),
                ('age_group', models.CharField(blank=True, max_length=20, null=True)),
                ('complaint_group', models.CharField(blank=True, max_length=30, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
