# Generated by Django 6.0.2 on 2026-03-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_villagecoordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagesession',
            name='geocoding_accuracy',
            field=models.CharField(blank=True, help_text='Spatial precision of geocoded coordinates', max_length=50, null=True, verbose_name='geocoding accuracy'),
        ),
        migrations.AddField(
            model_name='triagesession',
            name='geocoding_confidence',
            field=models.FloatField(blank=True, help_text='Geocoder confidence score (0.0 = unknown, 1.0 = exact match)', null=True, verbose_name='geocoding confidence'),
        ),
        migrations.AddField(
            model_name='triagesession',
            name='geocoding_display_name',
            field=models.CharField(blank=True, default='', help_text="Human-readable resolved address, e.g. 'Bwaise, Kawempe, Kampala, Uganda'", max_length=500, null=True, verbose_name='geocoding display name'),
        ),
        migrations.AddField(
            model_name='triagesession',
            name='geocoding_source',
            field=models.CharField(blank=True, help_text='How coordinates were obtained. Null = not yet geocoded', max_length=50, null=True, verbose_name='geocoding source'),
        ),
        migrations.AddField(
            model_name='triagesession',
            name='patient_phone_number',
            field=models.CharField(blank=True, help_text='Patient phone number for WhatsApp/SMS notifications', max_length=20, null=True, verbose_name='patient phone number'),
        ),
    ]
