# Generated by Django 6.0.2 on 2026-03-08 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0003_update_services_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'System Administrator'), ('facility_admin', 'Facility Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('clinical_officer', 'Clinical Officer'), ('receptionist', 'Receptionist'), ('staff', 'General Staff')], default='staff', help_text='User role within the facility', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('license_number', models.CharField(blank=True, help_text='Professional license number (for medical staff)', max_length=50, null=True)),
                ('department', models.CharField(blank=True, help_text='Department within the facility', max_length=100, null=True)),
                ('is_active_staff', models.BooleanField(default=True, help_text='Whether this staff member is currently active')),
                ('can_view_all_facilities', models.BooleanField(default=False, help_text='Can view cases from all facilities (admin only)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, help_text='Facility where this user works', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='facilities.facility')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
